name: Run Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Clojure CLI
        run: curl -O https://download.clojure.org/install/linux-install-1.11.1.1119.sh && chmod +x linux-install-1.11.1.1119.sh && sudo ./linux-install-1.11.1.1119.sh

      - name: Run ClojureScript Tests
        run: ME_ENV=ci clojure -M:test:cljs once

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Clean Build
        run: ./bin/clean

      - name: Build ClojureScript
        run: ME_ENV=production clojure -M:cljs once

      - name: Build CSS
        run: clojure -M:css once

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './resources/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
