name: Run Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Clojure CLI
        run: curl -O https://download.clojure.org/install/linux-install-1.11.1.1119.sh && chmod +x linux-install-1.11.1.1119.sh && sudo ./linux-install-1.11.1.1119.sh

      - name: Run ClojureScript Tests
        run: ME_ENV=ci clojure -M:test:cljs once

      - name: Run Clojure Tests
        run: clojure -M:test:spec

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Clone repository on remote machine
        env:
          REPO_URL: https://github.com/${{ github.repository }}
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USER }}
        run: |
          ssh $REMOTE_USER@$REMOTE_HOST << 'EOF'
            git clone $REPO_URL
            cd dnd-app
            # Optionally, list files to verify the clone
            ls -la
          EOF
