name: Run Build

on:
  push:
    branches:
      - master
      - stage
      - production

jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: brandoncorrea/clojure-base@v1
#
#      - name: Run ClojureScript Tests
#        run: ME_ENV=ci clojure -M:test:cljs once
#
#      - name: Run Clojure Tests
#        run: clojure -M:test:spec

  deploy:
    runs-on: ubuntu-latest
#    needs: test
    if: contains('stage production', github.ref_name)
    environment: ${{ github.ref_name }}

    concurrency:
      group: deploy-ec2-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: brandoncorrea/ec2-mono@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-image-id: ami-04a81a99f5ec58529
          aws-instance-type: t2.small
          aws-security-group-ids: ${{ secrets.SECURITY_GROUP_IDS }}
          aws-key-name: ${{ secrets.SSH_PRIVATE_KEY_NAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-user: ${{ secrets.SSH_USER }}
          app-name: ${{ vars.APP_NAME }}
          env-name: ${{ vars.ME_ENV }}
          install: |
            ./bin/install-java
            ./bin/install-clojure

            echo "Installing SSL"
            sudo echo "${{ secrets.SSL_CERTIFICATE }}" | sudo tee -a /etc/ssl/bwawan.com.crt > /dev/null
            sudo echo "${{ secrets.SSL_PRIVATE_KEY }}" | sudo tee -a /etc/ssl/bwawan.com.key > /dev/null

            echo "Installing Secrets"
            echo "ME_ENV=${{ vars.ME_ENV }}" >> .env
            echo "DOMAIN=${{ vars.DOMAIN }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

            clojure -M:test:cljs once
            clojure -M:test:css once

            ./bin/install-service ${{ vars.ME_ENV }}
            ./bin/install-nginx ${{ vars.DOMAIN }}
