name: Run Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Clojure CLI
        run: curl -O https://download.clojure.org/install/linux-install-1.11.1.1119.sh && chmod +x linux-install-1.11.1.1119.sh && sudo ./linux-install-1.11.1.1119.sh

      - name: Run ClojureScript Tests
        run: ME_ENV=ci clojure -M:test:cljs once

      - name: Run Clojure Tests
        run: clojure -M:test:spec

  deploy-stage:
    runs-on: ubuntu-latest
    #    needs: test
    environment: stage
    env:
      REMOTE_HOST: ${{ secrets.HOSTNAME }}
      REMOTE_USER: ${{ secrets.USER }}

    steps:
      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Stop Service
        run: |
          ssh -T $REMOTE_USER@$REMOTE_HOST << 'EOF'
            sudo systemctl stop dnd
          EOF

      - name: Inspect
        run: |
          echo "${{ github.server_url }}/${{ github.repository }}"

      - name: Clone Repository
        run: |
          ssh -T $REMOTE_USER@$REMOTE_HOST << 'EOF'
            rm -rf dnd
            echo "Repository: ${{ github.server_url }}/${{ github.repository }}"
            git clone "${{ github.server_url }}/${{ github.repository }}" dnd
          EOF

      - name: Install Secrets
        env:
          ME_ENV: ${{ github.environment }}
        run: |
          echo "ENV=$ME_ENV"
          ssh -T $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd dnd
            echo "ME_ENV=${{ secrets.ME_ENV }}" >> .env
            echo "HOSTNAME=${{ secrets.HOSTNAME }}" >> .env
          EOF

      - name: Install Service
        run: |
          ssh -T $REMOTE_USER@$REMOTE_HOST << 'EOF'
            clojure -M:test:cljs once
            clojure -M:test:css once
            sudo cp bin/stage.service /etc/systemd/system/dnd.service
            sudo systemctl daemon-reload
            sudo systemctl start dnd
          EOF
